In [3]:
import numpy as np
data = np.arange(0, 21,1)
print(data)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [9]:
# 0 是偶數
data[data%2==0]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [13]:
#我認知 0 是任何整數的倍數,因此取出3的倍數  應該要有 0的
data[data%3==0]

array([ 0,  3,  6,  9, 12, 15, 18])