# [作業目標]

1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```

2. 請試著在程式中印出以下三個 NdArray 的屬性？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


# 作業 

### 1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```


In [24]:
import numpy as np

#arange(15)  作用在於 生成一個 0 ~ 14 的array
#.reshape(3, 5) 作用在於將array 轉為 3x5陣列
dataList = np.arange(15).reshape(3, 5)
print(dataList)
#list(dataList) 只會把第一層的元素轉換成 List，多層的話只有第一層會轉
print('list(dataList): ', list(dataList))
#tolist() 才能達成多層的型態轉換
print('tolist(): ', dataList.tolist())

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
list(dataList):  [array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9]), array([10, 11, 12, 13, 14])]
tolist():  [[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14]]


2. 請試著在程式中印出以下三個 NdArray 的屬性並且解釋結果？（屬性：ndim、shape、size、dtype、itemsize、length、type）
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 

In [ ]:
# 記得先 Import 正確的套件

import numpy as np

In [66]:
#隨機建造一個最大數字小於10 長度為6的一為陣列 
a = np.random.randint(10, size=6) 
print(a)
#陣列的維度為 一維陣列
print (a.ndim)
#每一維度大小為6
print (a.shape)
#陣列當中有六個元素
print(a.size)
#陣列內容其資料型態 為 int
print(a.dtype)
#陣列中每個元素佔用的空間
print(a.itemsize)
#陣列長度為6
print(len(a))
#陣列型態為numpy.ndarray
print(type(a))

[3 9 8 8 8 1]
1
(6,)
6
int32
4
6
<class 'numpy.ndarray'>


In [84]:
#最大數字小於10 的 3*4 陣列
b = np.random.randint(10, size=(3,4)) 
print(b)
#陣列的維度為 二維陣列
print (b.ndim)
#每一維度大小為 第一維度 大小 3 第二維度 大小 4
print (b.shape)

#陣列當中有12個元素
print(b.size)
#陣列內容其資料型態 為 int
print(b.dtype)
#陣列中每個元素佔用的空間
print(b.itemsize)
#陣列長度為4
print(len(b))
#陣列型態為numpy.ndarray
print(type(b))

[[7 8 4 8]
 [9 8 9 3]
 [5 4 0 2]]
2
(3, 4)
---------------------------
12
int32
4
3
<class 'numpy.ndarray'>


In [87]:
#建立一個最大數字小於10 的 2*3*2陣列
#一維兩個元素 兩個元素分別內含三個元素 此三元素中裝兩個元素
c = np.random.randint(10, size=(2,3,2)) 
print(c)
#陣列的維度為 三維陣列
print (c.ndim)

#每一維度大小為 第一維度 長度2 第二維度長度3 第三維度長度2
print (c.shape)
#陣列當中有12個元素 2*3*2 = 12
print(c.size)
#陣列內容其資料型態 為 int
print(c.dtype)
#陣列中每個元素佔用的空間
print(c.itemsize)
#陣列長度為2 len 主要用於看第一維度的長度
print(len(c))
#陣列型態為numpy.ndarray
print(type(c))

[[[1 5]
  [2 4]
  [5 9]]

 [[1 9]
  [3 1]
  [8 4]]]
3
(2, 3, 2)
12
int32
4
2
<class 'numpy.ndarray'>


### 3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


In [ ]:
a = np.random.randint(10, size=6) 

print(a.tolist())
print(list(a))


[7, 6, 7, 3, 7, 5]
[7, 6, 7, 3, 7, 5]


In [ ]:
b = np.random.randint(10, size=(3,4)) 

print(b.tolist())
print(list(b))


[[5, 7, 4, 6], [9, 4, 0, 1], [9, 1, 2, 9]]
[array([5, 7, 4, 6]), array([9, 4, 0, 1]), array([9, 1, 2, 9])]


In [ ]:
c = np.random.randint(10, size=(2,3,2)) 

print(c.tolist())
print(list(c))


[[[0, 4], [0, 1], [9, 5]], [[8, 7], [8, 2], [6, 0]]]
[array([[0, 4],
       [0, 1],
       [9, 5]]), array([[8, 7],
       [8, 2],
       [6, 0]])]


In [171]:
def tolist(iterable):
    if type(iterable) != np.ndarray:
        return iterable
    newlist = []
    for obj in iterable:
        newlist.append(tolist(obj))
    return list(newlist)

print(tolist(a))

print(tolist(b))


print(tolist(c))

[3, 9, 8, 8, 8, 1]
[[7, 8, 4, 8], [9, 8, 9, 3], [5, 4, 0, 2]]
[[[1, 5], [2, 4], [5, 9]], [[1, 9], [3, 1], [8, 4]]]
